//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuYaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int ShipperID { get; set; }
        public int DriverID { get; set; }
        public Nullable<System.DateTime> CompletionDte { get; set; }
        public Nullable<int> Status { get; set; }
        public string Code { get; set; }
        public Nullable<int> MSA { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<int> OfferType { get; set; }
    }
}
