//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleOrderSearchConsole.SimpleSearchOrder {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchCriteria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SearchCriteria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int MSAField;
        
        private System.Nullable<System.DateTime> CompletionDteField;
        
        private int StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int MSA {
            get {
                return this.MSAField;
            }
            set {
                if ((this.MSAField.Equals(value) != true)) {
                    this.MSAField = value;
                    this.RaisePropertyChanged("MSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<System.DateTime> CompletionDte {
            get {
                return this.CompletionDteField;
            }
            set {
                if ((this.CompletionDteField.Equals(value) != true)) {
                    this.CompletionDteField = value;
                    this.RaisePropertyChanged("CompletionDte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int OrderIdField;
        
        private int ShipperIdField;
        
        private int DriverIdField;
        
        private System.Nullable<System.DateTime> CompletionDteField;
        
        private int StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        private int MSAField;
        
        private float DurationField;
        
        private int OfferTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ShipperId {
            get {
                return this.ShipperIdField;
            }
            set {
                if ((this.ShipperIdField.Equals(value) != true)) {
                    this.ShipperIdField = value;
                    this.RaisePropertyChanged("ShipperId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int DriverId {
            get {
                return this.DriverIdField;
            }
            set {
                if ((this.DriverIdField.Equals(value) != true)) {
                    this.DriverIdField = value;
                    this.RaisePropertyChanged("DriverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> CompletionDte {
            get {
                return this.CompletionDteField;
            }
            set {
                if ((this.CompletionDteField.Equals(value) != true)) {
                    this.CompletionDteField = value;
                    this.RaisePropertyChanged("CompletionDte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MSA {
            get {
                return this.MSAField;
            }
            set {
                if ((this.MSAField.Equals(value) != true)) {
                    this.MSAField = value;
                    this.RaisePropertyChanged("MSA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public float Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int OfferType {
            get {
                return this.OfferTypeField;
            }
            set {
                if ((this.OfferTypeField.Equals(value) != true)) {
                    this.OfferTypeField = value;
                    this.RaisePropertyChanged("OfferType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleSearchOrder.SearchOrderServiceSoap")]
    public interface SearchOrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse HelloWorld(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse> HelloWorldAsync(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestSearchOrder", ReplyAction="*")]
        void TestSearchOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TestSearchOrder", ReplyAction="*")]
        System.Threading.Tasks.Task TestSearchOrderAsync();
        
        // CODEGEN: Generating message contract since element name searchCriteria from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchOrder", ReplyAction="*")]
        SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse SearchOrder(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse> SearchOrderAsync(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchOrder", Namespace="http://tempuri.org/", Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequestBody Body;
        
        public SearchOrderRequest() {
        }
        
        public SearchOrderRequest(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.SearchCriteria searchCriteria;
        
        public SearchOrderRequestBody() {
        }
        
        public SearchOrderRequestBody(SimpleOrderSearchConsole.SimpleSearchOrder.SearchCriteria searchCriteria) {
            this.searchCriteria = searchCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponseBody Body;
        
        public SearchOrderResponse() {
        }
        
        public SearchOrderResponse(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SimpleOrderSearchConsole.SimpleSearchOrder.OrderInfo[] SearchOrderResult;
        
        public SearchOrderResponseBody() {
        }
        
        public SearchOrderResponseBody(SimpleOrderSearchConsole.SimpleSearchOrder.OrderInfo[] SearchOrderResult) {
            this.SearchOrderResult = SearchOrderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SearchOrderServiceSoapChannel : SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchOrderServiceSoapClient : System.ServiceModel.ClientBase<SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap>, SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap {
        
        public SearchOrderServiceSoapClient() {
        }
        
        public SearchOrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchOrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchOrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchOrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap.HelloWorld(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest inValue = new SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest();
            inValue.Body = new SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequestBody();
            SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse retVal = ((SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse> SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap.HelloWorldAsync(SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldResponse> HelloWorldAsync() {
            SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest inValue = new SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequest();
            inValue.Body = new SimpleOrderSearchConsole.SimpleSearchOrder.HelloWorldRequestBody();
            return ((SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public void TestSearchOrder() {
            base.Channel.TestSearchOrder();
        }
        
        public System.Threading.Tasks.Task TestSearchOrderAsync() {
            return base.Channel.TestSearchOrderAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap.SearchOrder(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest request) {
            return base.Channel.SearchOrder(request);
        }
        
        public SimpleOrderSearchConsole.SimpleSearchOrder.OrderInfo[] SearchOrder(SimpleOrderSearchConsole.SimpleSearchOrder.SearchCriteria searchCriteria) {
            SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest inValue = new SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest();
            inValue.Body = new SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequestBody();
            inValue.Body.searchCriteria = searchCriteria;
            SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse retVal = ((SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap)(this)).SearchOrder(inValue);
            return retVal.Body.SearchOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse> SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap.SearchOrderAsync(SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest request) {
            return base.Channel.SearchOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderResponse> SearchOrderAsync(SimpleOrderSearchConsole.SimpleSearchOrder.SearchCriteria searchCriteria) {
            SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest inValue = new SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequest();
            inValue.Body = new SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderRequestBody();
            inValue.Body.searchCriteria = searchCriteria;
            return ((SimpleOrderSearchConsole.SimpleSearchOrder.SearchOrderServiceSoap)(this)).SearchOrderAsync(inValue);
        }
    }
}
